export const QUERY_TEST_PLANS_MAX_TAKE = 1000;
export const QUERY_TEST_PLANS_REQUEST_PER_SECOND = 5;
export const QUERY_TEMPLATES_BATCH_SIZE = 1000;
export const QUERY_TEMPLATES_REQUEST_PER_SECOND = 5;
