import { editorTemplate, handleNumberValue, handleStringValue, keyValueExpressionBuilderCallback, numericKeyValueExpressionReaderCallback, stringKeyValueExpressionReaderCallback, valueTemplate } from "core/custom-query-builder-operations/key-value-operations";
import { QueryBuilderCustomOperation } from "smart-webcomponents-react";
import { dateTimeExpressionBuilderCallback } from "./custom-query-builder-operations/date-time-operations";
import { QueryOperation } from "./types";

export const queryBuilderMessages = {
  en: {
    propertyUnknownType: "'' property is with undefined 'type' member!",
    propertyInvalidValue: "Invalid '!",
    propertyInvalidValueType: "Invalid '!",
    elementNotInDOM: 'Element does not exist in DOM! Please, add the element to the DOM, before invoking a method.',
    moduleUndefined: 'Module is undefined.',
    missingReference: '.',
    htmlTemplateNotSuported: ": Browser doesn't support HTMLTemplate elements.",
    invalidTemplate: "' property accepts a string that must match the id of an HTMLTemplate element from the DOM.",
    add: 'Add',
    addCondition: 'Add Condition',
    addGroup: 'Add Group',
    and: 'And',
    notand: 'Not And',
    or: 'Or',
    notor: 'Not Or',
    '=': 'Equals',
    '<>': 'Does not equal',
    '>': 'Greater than',
    '>=': 'Greater than or equal to',
    '<': 'Less than',
    '<=': 'Less than or equal to',
    startswith: 'Starts with',
    endswith: 'Ends with',
    contains: 'Contains',
    notcontains: 'Does not contain',
    isblank: 'Is blank',
    isnotblank: 'Is not blank',
    wrongParentGroupIndex: "' method.",
    missingFields:
      ': Fields are required for proper condition\'s adding. Set "fields" source and then conditions will be added as expected.',
    wrongElementNode: "' method.",
    invalidDataStructure: ': Used invalid data structure in updateCondition/updateGroup method.',
    dateTabLabel: 'DATE',
    timeTabLabel: 'TIME',
    queryLabel: '',
  },
};

export enum FilterOperations {
  KeyValueMatch = 'key_value_matches',
  KeyValueDoesNotMatch = 'key_value_not_matches',
  KeyValueContains = 'key_value_contains',
  KeyValueDoesNotContains = 'key_value_not_contains',
  KeyValueIsGreaterThan = 'key_value_>',
  KeyValueIsGreaterThanOrEqual = 'key_value_>=',
  KeyValueIsLessThan = 'key_value_<',
  KeyValueIsLessThanOrEqual = 'key_value_<=',
  KeyValueIsNumericallyEqual = 'key_value_===',
  KeyValueIsNumericallyNotEqual = 'key_value_!==',
  DateTimeIsBlank = 'date_time_is_blank',
  DateTimeIsNotBlank = 'date_time_is_not_blank',
}

export enum FilterExpressions {
  KeyValueMatches = '{0}["{1}"] = "{2}"',
  KeyValueNotMatches = '{0}["{1}"] != "{2}"',
  KeyValueContains = '{0}["{1}"].Contains("{2}")',
  KeyValueNotContains = '!{0}["{1}"].Contains("{2}")',
  KeyValueIsGreaterThan = 'SafeConvert.ToDecimal({0}["{1}"]) > {2}',
  KeyValueIsGreaterThanOrEqual = 'SafeConvert.ToDecimal({0}["{1}"]) >= {2}',
  KeyValueIsLessThan = 'SafeConvert.ToDecimal({0}["{1}"]) < {2}',
  KeyValueIsLessThanOrEqual = 'SafeConvert.ToDecimal({0}["{1}"]) <= {2}',
  KeyValueIsNumericallyEqual = 'SafeConvert.ToDecimal({0}["{1}"]) = {2}',
  KeyValueIsNumericallyNotEqual = 'SafeConvert.ToDecimal({0}["{1}"]) != {2}',
  DateTimeIsBlank = '{0} == null || {0} == ""',
  DateTimeIsNotBlank = '{0} != null && {0} != ""',
}

export enum QueryOperationEnum {
  EQUALS = 'EQUALS',
  DOES_NOT_EQUAL = 'DOES_NOT_EQUAL',
  STARTS_WITH = 'STARTS_WITH',
  ENDS_WITH = 'ENDS_WITH',
  CONTAINS = 'CONTAINS',
  DOES_NOT_CONTAIN = 'DOES_NOT_CONTAIN',
  IS_BLANK = 'IS_BLANK',
  IS_NOT_BLANK = 'IS_NOT_BLANK',
  GREATER_THAN = 'GREATER_THAN',
  GREATER_THAN_OR_EQUAL_TO = 'GREATER_THAN_OR_EQUAL_TO',
  LESS_THAN = 'LESS_THAN',
  LESS_THAN_OR_EQUAL_TO = 'LESS_THAN_OR_EQUAL_TO',
  LIST_EQUALS = 'LIST_EQUALS',
  LIST_DOES_NOT_EQUAL = 'LIST_DOES_NOT_EQUAL',
  LIST_CONTAINS = 'LIST_CONTAINS',
  LIST_DOES_NOT_CONTAIN = 'LIST_DOES_NOT_CONTAIN',
  LIST_IS_EMPTY = 'LIST_IS_EMPTY',
  LIST_IS_NOT_EMPTY = 'LIST_IS_NOT_EMPTY',
  PROPERTY_EQUALS = 'PROPERTY_EQUALS',
  PROPERTY_DOES_NOT_EQUAL = 'PROPERTY_DOES_NOT_EQUAL',
  PROPERTY_STARTS_WITH = 'PROPERTY_STARTS_WITH',
  PROPERTY_ENDS_WITH = 'PROPERTY_ENDS_WITH',
  PROPERTY_CONTAINS = 'PROPERTY_CONTAINS',
  PROPERTY_DOES_NOT_CONTAIN = 'PROPERTY_DOES_NOT_CONTAIN',
  PROPERTY_IS_BLANK = 'PROPERTY_IS_BLANK',
  PROPERTY_IS_NOT_BLANK = 'PROPERTY_IS_NOT_BLANK',
  KEY_VALUE_MATCH = 'KEY_VALUE_MATCH',
  KEY_VALUE_DOES_NOT_MATCH = 'KEY_VALUE_DOES_NOT_MATCH',
  KEY_VALUE_DOES_NOT_CONTAINS = 'KEY_VALUE_DOES_NOT_CONTAINS',
  KEY_VALUE_CONTAINS = 'KEY_VALUE_CONTAINS',
  KEY_VALUE_IS_GREATER_THAN = 'KEY_VALUE_IS_GREATER_THAN',
  KEY_VALUE_IS_GREATER_THAN_OR_EQUAL = 'KEY_VALUE_IS_GREATER_THAN_OR_EQUAL',
  KEY_VALUE_IS_LESS_THAN = 'KEY_VALUE_IS_LESS_THAN',
  KEY_VALUE_IS_LESS_THAN_OR_EQUAL = 'KEY_VALUE_IS_LESS_THAN_OR_EQUAL',
  KEY_VALUE_IS_NUMERICAL_EQUAL = 'KEY_VALUE_IS_NUMERICAL_EQUAL',
  KEY_VALUE_IS_NUMERICAL_NOT_EQUAL = 'KEY_VALUE_IS_NUMERICAL_NOT_EQUAL',
  DATE_TIME_IS_AFTER = 'DATE_TIME_IS_AFTER',
  DATE_TIME_IS_BEFORE = 'DATE_TIME_IS_BEFORE',
  DATE_TIME_IS_BLANK = 'DATE_TIME_IS_BLANK',
  DATE_TIME_IS_NOT_BLANK = 'DATE_TIME_IS_NOT_BLANK',
}

export const QueryBuilderOperations: Record<QueryOperationEnum, QueryOperation> = {
  EQUALS: {
    label: 'equals',
    name: '=',
    expressionTemplate: '{0} = "{1}"',
  },
  DOES_NOT_EQUAL: {
    label: 'does not equal',
    name: '<>',
    expressionTemplate: '{0} != "{1}"',
  },
  STARTS_WITH: {
    label: 'starts with',
    name: 'startswith',
    expressionTemplate: '{0}.StartsWith("{1}")',
  },
  ENDS_WITH: {
    label: 'ends with',
    name: 'endswith',
    expressionTemplate: '{0}.EndsWith("{1}")',
  },
  CONTAINS: {
    label: 'contains',
    name: 'contains',
    expressionTemplate: '{0}.Contains("{1}")',
  },
  DOES_NOT_CONTAIN: {
    label: 'does not contain',
    name: 'notcontains',
    expressionTemplate: '!({0}.Contains("{1}"))',
  },
  IS_BLANK: {
    label: 'is blank',
    name: 'isblank',
    expressionTemplate: 'string.IsNullOrEmpty({0})',
    hideValue: true,
  },
  IS_NOT_BLANK: {
    label: 'is not blank',
    name: 'isnotblank',
    expressionTemplate: '!string.IsNullOrEmpty({0})',
    hideValue: true,
  },
  GREATER_THAN: {
    label: 'greater than',
    name: '>',
    expressionTemplate: '{0} > "{1}"',
  },
  GREATER_THAN_OR_EQUAL_TO: {
    label: 'greater than or equal to',
    name: '>=',
    expressionTemplate: '{0} >= "{1}"',
  },
  LESS_THAN: {
    label: 'less than',
    name: '<',
    expressionTemplate: '{0} < "{1}"',
  },
  LESS_THAN_OR_EQUAL_TO: {
    label: 'less than or equal to',
    name: '<=',
    expressionTemplate: '{0} <= "{1}"',
  },
  // List expressions
  LIST_EQUALS: {
    label: 'equals',
    name: 'listequals',
    expressionTemplate: '{0}.Contains("{1}")',
  },
  LIST_DOES_NOT_EQUAL: {
    label: 'does not equal',
    name: 'listnotequals',
    expressionTemplate: '!({0}.Contains("{1}"))',
  },
  LIST_CONTAINS: {
    label: 'contains',
    name: 'listcontains',
    expressionTemplate: '{0}.Any(it.Contains("{1}"))',
  },
  LIST_DOES_NOT_CONTAIN: {
    label: 'does not contain',
    name: 'listnotcontains',
    expressionTemplate: '{0}.Any(!it.Contains("{1}"))',
  },
  LIST_IS_EMPTY: {
    label: 'is empty',
    name: 'listisempty',
    expressionTemplate: '{0}.Count == 0',
    hideValue: true,
  },
  LIST_IS_NOT_EMPTY: {
    label: 'is not empty',
    name: 'listisnotempty',
    expressionTemplate: '{0}.Count > 0',
    hideValue: true,
  },
  // Properties expressions
  PROPERTY_EQUALS: {
    label: 'equals',
    name: 'propertyequals',
    expressionTemplate: 'properties["{0}"] = "{1}"',
  },
  PROPERTY_DOES_NOT_EQUAL: {
    label: 'does not equal',
    name: 'propertynotequals',
    expressionTemplate: 'properties["{0}"] != "{1}"',
  },
  PROPERTY_STARTS_WITH: {
    label: 'starts with',
    name: 'propertystartswith',
    expressionTemplate: 'properties["{0}"].StartsWith("{1}")',
  },
  PROPERTY_ENDS_WITH: {
    label: 'ends with',
    name: 'propertyendswith',
    expressionTemplate: 'properties["{0}"].EndsWith("{1}")',
  },
  PROPERTY_CONTAINS: {
    label: 'contains',
    name: 'propertycontains',
    expressionTemplate: 'properties["{0}"].Contains("{1}")',
  },
  PROPERTY_DOES_NOT_CONTAIN: {
    label: 'does not contain',
    name: 'propertynotcontains',
    expressionTemplate: '!(properties["{0}"].Contains("{1}"))',
  },
  PROPERTY_IS_BLANK: {
    label: 'is blank',
    name: 'propertyisblank',
    expressionTemplate: 'string.IsNullOrEmpty(properties["{0}"])',
    hideValue: true,
  },
  PROPERTY_IS_NOT_BLANK: {
    label: 'is not blank',
    name: 'propertyisnotblank',
    expressionTemplate: '!string.IsNullOrEmpty(properties["{0}"])',
    hideValue: true,
  },
  KEY_VALUE_MATCH: {
    label: `matches`,
    name: FilterOperations.KeyValueMatch,
    expressionTemplate: FilterExpressions.KeyValueMatches,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleStringValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: stringKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_DOES_NOT_MATCH: {
    label: `does not match`,
    name: FilterOperations.KeyValueDoesNotMatch,
    expressionTemplate: FilterExpressions.KeyValueNotMatches,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleStringValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: stringKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_DOES_NOT_CONTAINS: {
    label: `does not contain`,
    name: FilterOperations.KeyValueDoesNotContains,
    expressionTemplate: FilterExpressions.KeyValueNotContains,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleStringValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: stringKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_CONTAINS: {
    label: `contains`,
    name: FilterOperations.KeyValueContains,
    expressionTemplate: FilterExpressions.KeyValueContains,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleStringValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: stringKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_IS_GREATER_THAN: {
    label: `> (numeric)`,
    name: FilterOperations.KeyValueIsGreaterThan,
    expressionTemplate: FilterExpressions.KeyValueIsGreaterThan,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleNumberValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: numericKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_IS_GREATER_THAN_OR_EQUAL: {
    label: `≥ (numeric)`,
    name: FilterOperations.KeyValueIsGreaterThanOrEqual,
    expressionTemplate: FilterExpressions.KeyValueIsGreaterThanOrEqual,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleNumberValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: numericKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_IS_LESS_THAN: {
    label: `< (numeric)`,
    name: FilterOperations.KeyValueIsLessThan,
    expressionTemplate: FilterExpressions.KeyValueIsLessThan,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleNumberValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: numericKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_IS_LESS_THAN_OR_EQUAL: {
    label: `≤ (numeric)`,
    name: FilterOperations.KeyValueIsLessThanOrEqual,
    expressionTemplate: FilterExpressions.KeyValueIsLessThanOrEqual,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleNumberValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: numericKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_IS_NUMERICAL_EQUAL: {
    label: `= (numeric)`,
    name: FilterOperations.KeyValueIsNumericallyEqual,
    expressionTemplate: FilterExpressions.KeyValueIsNumericallyEqual,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleNumberValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: numericKeyValueExpressionReaderCallback,
  },
  KEY_VALUE_IS_NUMERICAL_NOT_EQUAL: {
    label: `≠ (numeric)`,
    name: FilterOperations.KeyValueIsNumericallyNotEqual,
    expressionTemplate: FilterExpressions.KeyValueIsNumericallyNotEqual,
    editorTemplate: editorTemplate,
    valueTemplate: valueTemplate,
    handleValue: handleNumberValue,
    expressionBuilderCallback: keyValueExpressionBuilderCallback,
    expressionReaderCallback: numericKeyValueExpressionReaderCallback,
  },
  // DateTime expressions
  DATE_TIME_IS_AFTER: {
    label: 'is after',
    name: 'isafter',
    expressionTemplate: '{0} > "{1}"',
  },
  DATE_TIME_IS_BEFORE: {
    label: 'is before',
    name: 'isbefore',
    expressionTemplate: '{0} < "{1}"',
  },
  DATE_TIME_IS_BLANK: {
    label: 'is blank',
    name: FilterOperations.DateTimeIsBlank,
    expressionTemplate: FilterExpressions.DateTimeIsBlank,
    expressionBuilderCallback: dateTimeExpressionBuilderCallback,
    hideValue: true,
  },
  DATE_TIME_IS_NOT_BLANK: {
    label: 'is not blank',
    name: FilterOperations.DateTimeIsNotBlank,
    expressionTemplate: FilterExpressions.DateTimeIsNotBlank,
    expressionBuilderCallback: dateTimeExpressionBuilderCallback,
    hideValue: true,
  },
};

export const customOperations: QueryBuilderCustomOperation[] = [
    QueryBuilderOperations.EQUALS,
    QueryBuilderOperations.DOES_NOT_EQUAL,
    QueryBuilderOperations.STARTS_WITH,
    QueryBuilderOperations.ENDS_WITH,
    QueryBuilderOperations.CONTAINS,
    QueryBuilderOperations.DOES_NOT_CONTAIN,
    QueryBuilderOperations.IS_BLANK,
    QueryBuilderOperations.IS_NOT_BLANK,
    QueryBuilderOperations.GREATER_THAN,
    QueryBuilderOperations.GREATER_THAN_OR_EQUAL_TO,
    QueryBuilderOperations.LESS_THAN,
    QueryBuilderOperations.LESS_THAN_OR_EQUAL_TO,
    QueryBuilderOperations.LIST_EQUALS,
    QueryBuilderOperations.LIST_DOES_NOT_EQUAL,
    QueryBuilderOperations.LIST_CONTAINS,
    QueryBuilderOperations.LIST_DOES_NOT_CONTAIN,
    QueryBuilderOperations.PROPERTY_EQUALS,
    QueryBuilderOperations.PROPERTY_DOES_NOT_EQUAL,
    QueryBuilderOperations.PROPERTY_STARTS_WITH,
    QueryBuilderOperations.PROPERTY_ENDS_WITH,
    QueryBuilderOperations.PROPERTY_CONTAINS,
    QueryBuilderOperations.PROPERTY_DOES_NOT_CONTAIN,
    QueryBuilderOperations.PROPERTY_IS_BLANK,
    QueryBuilderOperations.PROPERTY_IS_NOT_BLANK,
    QueryBuilderOperations.DATE_TIME_IS_AFTER,
    QueryBuilderOperations.DATE_TIME_IS_BEFORE,
  ];
