export enum allAssetListProperties {
    vendor_name = 'vendor name',
    name = 'name',
    model_name = 'model name',
    workspace = 'workspace',
    location = 'location',
    id = 'id',
    serial_number = 'serial number',
    model_number = 'model number',
    vendor_number = 'vendor number',
    asset_type = 'asset type',
    firmware_version = 'firmware version',
    visa_resource_name = 'visa resource name',
    part_number = 'part number',
    last_updated_timestamp = 'last updated timestamp',
    bus_type = 'bus type',
    is_NI_asset = 'is NI asset',
    keywords = 'keywords',
    properties = 'properties',
    minionId = 'minionId',
    parent_name = 'parent name',
    supports_self_calibration = 'supports self calibration',
    supports_self_test = 'supports self test',
    supports_reset = 'supports reset',
    discovery_type = 'discovery type',
    self_calibration = 'self calibration',
    supports_external_calibration = 'supports external calibration',
    calibration_due_date = 'calibration due date',
    is_system_controller = 'is system controller',
    calibration_status = 'calibration status',
    scan_code = 'scan code'
};

export const nonDefaultAssetListProperties = [
    allAssetListProperties.id,
    allAssetListProperties.serial_number,
    allAssetListProperties.model_number,
    allAssetListProperties.vendor_number,
    allAssetListProperties.asset_type,
    allAssetListProperties.firmware_version,
    allAssetListProperties.visa_resource_name,
    allAssetListProperties.part_number,
    allAssetListProperties.last_updated_timestamp,
    allAssetListProperties.bus_type,
    allAssetListProperties.is_NI_asset,
    allAssetListProperties.keywords,
    allAssetListProperties.properties,
    allAssetListProperties.minionId,
    allAssetListProperties.parent_name,
    allAssetListProperties.supports_self_calibration,
    allAssetListProperties.supports_self_test,
    allAssetListProperties.supports_reset,
    allAssetListProperties.discovery_type,
    allAssetListProperties.self_calibration,
    allAssetListProperties.supports_external_calibration,
    allAssetListProperties.calibration_due_date,
    allAssetListProperties.is_system_controller,
    allAssetListProperties.calibration_status,
    allAssetListProperties.scan_code
];

export const timeOutPeriod = 10000;
