export enum assetColumn {
    vendor_name = 'vendor name',
    name = 'name',
    model_name = 'model name',
    workspace = 'workspace',
    location = 'location',
    id = 'id',
    serial_number = 'serial number',
    model_number = 'model number',
    vendor_number = 'vendor number',
    asset_type = 'asset type',
    firmware_version = 'firmware version',
    visa_resource_name = 'visa resource name',
    part_number = 'part number',
    last_updated_timestamp = 'last updated timestamp',
    bus_type = 'bus type',
    is_NI_asset = 'is NI asset',
    keywords = 'keywords',
    properties = 'properties',
    minionId = 'minionId',
    parent_name = 'parent name',
    supports_self_calibration = 'supports self calibration',
    supports_self_test = 'supports self test',
    supports_reset = 'supports reset',
    discovery_type = 'discovery type',
    self_calibration = 'self calibration',
    supports_external_calibration = 'supports external calibration',
    calibration_due_date = 'calibration due date',
    is_system_controller = 'is system controller',
    calibration_status = 'calibration status',
    scan_code = 'scan code'
};

export const nonDefaultAssetListProperties = [
    assetColumn.id,
    assetColumn.serial_number,
    assetColumn.model_number,
    assetColumn.vendor_number,
    assetColumn.asset_type,
    assetColumn.firmware_version,
    assetColumn.visa_resource_name,
    assetColumn.part_number,
    assetColumn.last_updated_timestamp,
    assetColumn.bus_type,
    assetColumn.is_NI_asset,
    assetColumn.keywords,
    assetColumn.properties,
    assetColumn.minionId,
    assetColumn.parent_name,
    assetColumn.supports_self_calibration,
    assetColumn.supports_self_test,
    assetColumn.supports_reset,
    assetColumn.discovery_type,
    assetColumn.self_calibration,
    assetColumn.supports_external_calibration,
    assetColumn.calibration_due_date,
    assetColumn.is_system_controller,
    assetColumn.calibration_status,
    assetColumn.scan_code
];

export const timeOutPeriod = 10000;
