export const workItemColumn = {
    id: 'Work item ID',
    name: 'Work item name',
    type: 'Work item type',
    state: 'State',
    substate: 'Substate',
    description: 'Description',
    testProgram: 'Test program',
    partNumber: 'Part number',
    productName: 'Product name',
    productId: 'Product ID',
    workspace: 'Workspace',
    assignedTo: 'Assigned to',
    requestedBy: 'Requested by',
    createdBy: 'Created by',
    updatedBy: 'Updated by',
    createdAt: 'Created at',
    updatedAt: 'Updated at',
    parentWorkItemName: 'Work order name',
    parentWorkItemId: 'Work order ID',
    templateId: 'Template ID',
    earliestStartDate: 'Earliest start date',
    dueDate: 'Due date',
    estimatedDuration: 'Estimated duration',
    plannedStartDate: 'Planned start date',
    plannedEndDate: 'Planned end date',
    plannedDuration: 'Planned duration',
    assetId: 'Asset ID',
    systemName: 'System name',
    targetLocation: 'Target location',
    targetParent: 'Target parent',
    targetLocationAsset: 'Target Location (Asset)',
    targetParentAsset: 'Target Parent (Asset)',
    targetLocationDut: 'Target Location (DUT)',
    targetParentDut: 'Target Parent (DUT)',
};

export const nonDefaultWorkItemProperties = [
    workItemColumn.id,
    workItemColumn.type,
    workItemColumn.substate,
    workItemColumn.description,
    workItemColumn.testProgram,
    workItemColumn.partNumber,
    workItemColumn.productName,
    workItemColumn.productId,
    workItemColumn.workspace,
    workItemColumn.requestedBy,
    workItemColumn.createdBy,
    workItemColumn.updatedBy,
    workItemColumn.parentWorkItemName,
    workItemColumn.parentWorkItemId,
    workItemColumn.templateId,
    workItemColumn.estimatedDuration,
    workItemColumn.plannedDuration,
    workItemColumn.systemName,
];

